# This is a basic workflow to help you get started with Actions

name: build-and-deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: "refs/heads/deploy"
          path: "public"
      - name: yarn build (deploy)
        if: github.ref == 'refs/heads/master'
        run: |
          yarn install
          yarn build
          cd public
          git rm -rf . || true
          git clean -fxd
          cd ..
          cp -R dist/* public/
      - name: Commit files
        if: github.ref == 'refs/heads/master'
        run: |
          cd public
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "[actions] deploy" --allow-empty
      - name: GitHub Push
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: deploy
          directory: public
          force_with_lease: true
